### ISSUE TITLE
[BUG] got 2 error log here

### ISSUE THREAD

**Issue by CoolLKKPS** [TheAnsuz/Lethal-Company-Configurable-Company-API#77]
[Error  :Configurable Company Variables] Unable to patch LCV.Patch.TimeOfDayPatch: IL Compile Error (unknown location)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LCVCompat.GameItem.GetAssigned (Item item, System.Boolean createIfMissing) (at <8a6c70ed0bab4dbfaf521e438d2633c4>:IL_0000)
LCVCompat.GameItemRarityList.Create (System.Collections.Generic.IEnumerable`1[SpawnableItemWithRarity][] rarities) (at <8a6c70ed0bab4dbfaf521e438d2633c4>:IL_001F)
LCVCompat.GameLevelConfig..ctor (SelectableLevel level) (at <8a6c70ed0bab4dbfaf521e438d2633c4>:IL_00EB)
LCVCompat.GameLevel..ctor (SelectableLevel level) (at <8a6c70ed0bab4dbfaf521e438d2633c4>:IL_0000)
LCVCompat.GameLevel.Assign (SelectableLevel level) (at <8a6c70ed0bab4dbfaf521e438d2633c4>:IL_003C)
LCV.Patch.SelectableLevelPatch.Awake_Postfix (SelectableLevel __instance) (at <d4beb0ff746b4132923fcaffa557e90a>:IL_0073)
(wrapper dynamic-method) SelectableLevel.DMD<SelectableLevel::Awake>(SelectableLevel)
UnityEngine.AssetBundle:LoadAllAssets()
LethalLevelLoader.<LoadBundle>d__34:MoveNext() (at ./Tools/AssetBundleLoader.cs:169)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by CoolLKKPS** [comment]
Modpack Shared Link: https://1drv.ms/f/c/c26722dc35962b5c/ElwrljXcImcggMKLCgAAAAABXdwXiAVT3j3zNnyNZw3uXg

**Comment by TheAnsuz** [comment]
Hello @CoolLKKPS 

This issue was due to an update of lethal company which broke some parts of LCV, this issue has been resolved with LCV 2.7.0.

Let me know if you experience further issues.

**Comment by CoolLKKPS** [comment]
@TheAnsuz thx for the reply, i still have this error log that i don't know what its mean
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LCVCompat.GameItem.GetAssigned (Item item, System.Boolean createIfMissing) (at <693fca1e15ea4bb9aba66a91408bce83>:IL_0000)
LCVCompat.GameItemRarityList.Create (System.Collections.Generic.IEnumerable`1[SpawnableItemWithRarity][] rarities) (at <693fca1e15ea4bb9aba66a91408bce83>:IL_001F)
LCVCompat.GameLevelConfig..ctor (SelectableLevel level) (at <693fca1e15ea4bb9aba66a91408bce83>:IL_00EB)
LCVCompat.GameLevel..ctor (SelectableLevel level) (at <693fca1e15ea4bb9aba66a91408bce83>:IL_0000)
LCVCompat.GameLevel.Assign (SelectableLevel level) (at <693fca1e15ea4bb9aba66a91408bce83>:IL_003C)
LCV.Patch.SelectableLevelPatch.Awake_Postfix (SelectableLevel __instance) (at <8b0b92f1270d4a67ace6482ccd7006dc>:IL_0073)
(wrapper dynamic-method) SelectableLevel.DMD<SelectableLevel::Awake>(SelectableLevel)
UnityEngine.AssetBundle:LoadAllAssets()
LethalLevelLoader.<LoadBundle>d__34:MoveNext() (at ./Tools/AssetBundleLoader.cs:169)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by CoolLKKPS** [comment]
https://thunderstore.io/c/lethal-company/p/IAmBatby/LethalLevelLoader
https://thunderstore.io/c/lethal-company/p/Skeletonek/LethalLevelLoaderAOORE_Fix

**Comment by TheAnsuz** [comment]
Hello @CoolLKKPS 

Seems like an issue with LCV trying to register an invalid Item, this might be due to other mod not having updated to v65, if you find all configurations for every item you can ignore this error (might be a dummy object from other mod and LCV is just picking it up)

If you would like further assistance, you can post/check the mod adding that item and open an issue on their mod.

Let me know if you have any other issues!

**Comment by CoolLKKPS** [comment]
thx, i found this issue was from this custom planet mod: https://thunderstore.io/c/lethal-company/p/LethalMatt/Outpost_31/
